export const NFL_TEAMS = [
  { value: "arizona-cardinals", label: "Arizona Cardinals", abbr: "ARI" },
  { value: "atlanta-falcons", label: "Atlanta Falcons", abbr: "ATL" },
  { value: "baltimore-ravens", label: "Baltimore Ravens", abbr: "BAL" },
  { value: "buffalo-bills", label: "Buffalo Bills", abbr: "BUF" },
  { value: "carolina-panthers", label: "Carolina Panthers", abbr: "CAR" },
  { value: "chicago-bears", label: "Chicago Bears", abbr: "CHI" },
  { value: "cincinnati-bengals", label: "Cincinnati Bengals", abbr: "CIN" },
  { value: "cleveland-browns", label: "Cleveland Browns", abbr: "CLE" },
  { value: "dallas-cowboys", label: "Dallas Cowboys", abbr: "DAL" },
  { value: "denver-broncos", label: "Denver Broncos", abbr: "DEN" },
  { value: "detroit-lions", label: "Detroit Lions", abbr: "DET" },
  { value: "green-bay-packers", label: "Green Bay Packers", abbr: "GB" },
  { value: "houston-texans", label: "Houston Texans", abbr: "HOU" },
  { value: "indianapolis-colts", label: "Indianapolis Colts", abbr: "IND" },
  { value: "jacksonville-jaguars", label: "Jacksonville Jaguars", abbr: "JAX" },
  { value: "kansas-city-chiefs", label: "Kansas City Chiefs", abbr: "KC" },
  { value: "las-vegas-raiders", label: "Las Vegas Raiders", abbr: "LV" },
  { value: "los-angeles-chargers", label: "Los Angeles Chargers", abbr: "LAC" },
  { value: "los-angeles-rams", label: "Los Angeles Rams", abbr: "LAR" },
  { value: "miami-dolphins", label: "Miami Dolphins", abbr: "MIA" },
  { value: "minnesota-vikings", label: "Minnesota Vikings", abbr: "MIN" },
  { value: "new-england-patriots", label: "New England Patriots", abbr: "NE" },
  { value: "new-orleans-saints", label: "New Orleans Saints", abbr: "NO" },
  { value: "new-york-giants", label: "New York Giants", abbr: "NYG" },
  { value: "new-york-jets", label: "New York Jets", abbr: "NYJ" },
  { value: "philadelphia-eagles", label: "Philadelphia Eagles", abbr: "PHI" },
  { value: "pittsburgh-steelers", label: "Pittsburgh Steelers", abbr: "PIT" },
  { value: "san-francisco-49ers", label: "San Francisco 49ers", abbr: "SF" },
  { value: "seattle-seahawks", label: "Seattle Seahawks", abbr: "SEA" },
  { value: "tampa-bay-buccaneers", label: "Tampa Bay Buccaneers", abbr: "TB" },
  { value: "tennessee-titans", label: "Tennessee Titans", abbr: "TEN" },
  {
    value: "washington-commanders",
    label: "Washington Commanders",
    abbr: "WAS",
  },
] as const;
